version = "0.1.0"
author = "ABC Authors"
description = "Asynchronous Blockchain"
license = "MIT"

requires "questionable >= 0.10.0 & < 0.11.0"
requires "blscurve"
requires "nimcrypto"
requires "stint"
requires "stew"
